version: '3.8'
services:
    database:
        image: "postgres:12.3-alpine"
        shm_size: '2g'
        environment:
            - POSTGRES_USER=student
            - POSTGRES_PASSWORD=student
            - POSTGRES_DB=studentdb
        ports:
            - "5432:5432"
        restart: always
